import 'package:flutter/material.dart';

const Locale LOCALE_ENGLISH = Locale('en', 'US');
const Locale LOCALE_BANGLA = Locale('bn', 'BD');

const STR_APP_NAME = 'app_name';
const STR_SIGN_IN = 'sign_in';
const STR_EMAIL = 'email';
const STR_PASSWORD = 'password';
const STR_FORGOT_PASSWORD = 'forgot_password';
const STR_LOGIN = 'login';
const STR_CREATE_NEW_ACCOUNT = 'create_new_account';
const STR_USERNAME = 'username';
const STR_CONFIRM_PASSWORD = 'confirm_password';
const STR_ALREADY_SIGNED = 'already_signup';
const STR_SIGNUP = 'signup';
const STR_REQUIRED = 'required';
const STR_INVALID_EMAIL = 'invalid_email';
const STR_PASSWORD_LENGTH_SHORT = 'must_be_4_char';
const STR_CONFIRM_PASSWORD_MISMATCH = 'confirm_password_mismatch';
const STR_NO_INTERNET = 'no_internet';
const STR_INACTIVE_CONNECTION = 'inactive_connection';
const STR_TIMED_OUT = 'timed_out';
const STR_UNKNOWN_ERROR = 'unknown_error';
const STR_SUCCESS = 'success';
const STR_FAILED = 'failed';
const STR_PRODUCT_LIST = 'product_list';
const STR_MY_ACCOUNT = 'my_account';
const STR_SOLD = 'sold';
const STR_FILTER = 'filter';
const STR_SORT_BY = 'sort_by';